### ISSUE TITLE
Change `cfp.yml` file struct

### ISSUE THREAD

**Issue by blablatdinov** [yegor256/awesome-cfp#65]
Currently yaml file format:

```yaml
"PLDI":
  - year: 2025
  - url: "https://conf.researchr.org/series/pldi"
  - publisher: ACM
  - rank: "A*"
  - core: "https://portal.core.edu.au/conf-ranks/84"
  - scope: PL
  - short:
  - full: 20
  - format: 1C
  - cfp:
  - country: DK
```

convert to json:

```json
{
  "PLDI": [
    {"year": 2025},
    {"url": "https://conf.researchr.org/series/pldi"},
    {"publisher": "ACM"},
    {"rank": "A*"},
    {"core": "https://portal.core.edu.au/conf-ranks/84"},
    {"scope": "PL"},
    {"short": null},
    {"full": 20},
    {"format": "1C"},
    {"cfp": null},
    {"country": "DK"}
  ]
}
```

I suggest next format, where conference info fields placed in one object:

```yaml
"PLDI":
  year: 2025
  url: "https://conf.researchr.org/series/pldi"
  publisher: ACM
  rank: "A*"
  core: "https://portal.core.edu.au/conf-ranks/84"
  scope: PL
  short:
  full: 20
  format: 1C
  cfp:
  country: DK
```
